import React from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";

function Disclaimer() {

  const navigate = useNavigate();

  return (

    <div style={styles.page}>

      <motion.div
        initial={{ opacity: 0, y: 40 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.7 }}
        style={styles.card}
      >

        <motion.h1
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.2 }}
          style={styles.title}
        >
          Disclaimer
        </motion.h1>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          style={styles.text}
        >

          This AI system is intended for <b>educational screening purposes only</b>.
          It does <b>not provide medical diagnosis or treatment recommendations</b>.

          <br /><br />

          If you suspect symptoms related to ADHD, please consult a
          <b> licensed medical professional</b>.

          <br /><br />

          The results generated by MindBloom are based on machine learning
          patterns and should be used <b>only as a preliminary self-assessment tool</b>.

        </motion.p>

        <motion.button
          whileHover={{ scale: 1.08 }}
          whileTap={{ scale: 0.95 }}
          transition={{ type: "spring", stiffness: 200 }}
          style={styles.button}
          onClick={() => navigate("/userinfo")}
        >
          I Understand — Continue
        </motion.button>

      </motion.div>

    </div>

  );
}

const styles = {

  page: {
    height: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "linear-gradient(135deg,#0f172a,#1e293b)",
    fontFamily: "sans-serif"
  },

  card: {
    width: "500px",
    padding: "40px",
    borderRadius: "20px",
    background: "rgba(255,255,255,0.06)",
    backdropFilter: "blur(10px)",
    border: "1px solid rgba(255,255,255,0.15)",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    boxShadow: "0 20px 40px rgba(0,0,0,0.4)"
  },

  title: {
    color: "white",
    textAlign: "center",
    fontSize: "32px"
  },

  text: {
    color: "rgba(255,255,255,0.85)",
    lineHeight: "1.6",
    fontSize: "15px"
  },

  button: {
    marginTop: "10px",
    padding: "14px",
    borderRadius: "30px",
    border: "none",
    fontSize: "16px",
    cursor: "pointer",
    background: "linear-gradient(90deg,#6366f1,#22c55e)",
    color: "white",
    fontWeight: "bold"
  }

};

export default Disclaimer;

